version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.16
executors:
  node-executor:
    docker:
      - image: cimg/node:14.10.0
    resource_class: small
    working_directory: ~/mars-mission
jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: mars-mission-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: mars-mission-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run test:coverage
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: node-executor
    steps:
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - attach_workspace:
          at: ~/mars-mission
      - run: npm install
      - run: npm run build:integration
      - aws-s3/sync:
          from: ~/mars-mission/build
          to: 's3://mars-mission-integration'
workflows:
  on_commit:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
