version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.16
jobs:
  test:
    docker:
      - image: cimg/node:14.10.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test:coverage
      - run: npm run lint
  deploy:
    docker:
      - image: cimg/node:14.10.0
    steps:
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: 's3://mars-mission-integration'
workflows:
  on_commit:
    jobs:
      - test
      - deploy:
        requires: 
          - test
        filters:
          branches:
            only: master