version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.16
executors:
  node-executor:
    docker:
      - image: cimg/node:14.10.0
    working_directory: /tmp
jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: workspace
          paths:
            - *
      - run: npm run test:coverage
      - run: npm run lint
  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: 's3://mars-mission-integration'
workflows:
  version: 2
  on_commit:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master