version: 2.1
jobs:
  build_test_deploy:
    docker:
      - image: cimg/node:14.10.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  test:
    docker:
      - image: cimg/node:14.10.0
    steps:
      - run: npm run test:coverage
workflows:
  on_commit:
    jobs:
      - build_test_deploy          